<a href="https://colab.research.google.com/github/AshaS591/Data-Analytics/blob/main/Data_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
name='Asha'
name

'Asha'

*Description* *Description*

In [ ]:
a=[39,2762,90,74]
print(a)
name

[39, 2762, 90, 74]


'Asha'

In [ ]:
import numpy as np

In [ ]:
Names=['asha','anu','shashi','vasu',10,257.9,344
]

In [ ]:
arr=np.array(Names)
arr

array(['asha', 'anu', 'shashi', 'vasu', '10', '257.9', '344'],
      dtype='<U32')

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(7,)

In [ ]:
np.random.choice(Names)

'vasu'

In [ ]:
np.random.shuffle(Names)
Names

['anu', 10, 257.9, 'vasu', 344, 'asha', 'shashi']

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros ((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((3,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((4,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.identity (4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity (6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
import pandas as pd

In [ ]:
Emp={'Ename':['asha','anu','arya','ram','anju'],
'Eid':[201,202,203,204,205],
'Sal':[50000,30000,40909,32000,80000],
'Dept_no':[1,2,3,4,5],
'Dname':['development ','accounting','sales','research ','Testing ']}

In [ ]:
df=pd.DataFrame(Emp)
df

Ename  Eid    Sal  Dept_no         Dname
0  asha  201  50000        1  development 
1   anu  202  30000        2    accounting
2  arya  203  40909        3         sales
3   ram  204  32000        4     research 
4  anju  205  80000        5      Testing

#Accessing  using column name
df[column name]

In [ ]:
df['Ename']

0    asha
1     anu
2    arya
3     ram
4    anju
Name: Ename, dtype: object

In [ ]:
df['Sal']

0    50000
1    30000
2    40909
3    32000
4    80000
Name: Sal, dtype: int64

#To fetch particular element
#df([cn][index])

In [ ]:
df['Ename'][1]

'anu'

In [ ]:
df['Ename'][3]

'ram'

In [ ]:
df['Dname'][3]

'research '

In [ ]:
df[::2]

Ename  Eid    Sal  Dept_no         Dname
0  asha  201  50000        1  development 
2  arya  203  40909        3         sales
4  anju  205  80000        5      Testing

In [ ]:
df[1::2]

Ename  Eid    Sal  Dept_no       Dname
1   anu  202  30000        2  accounting
3   ram  204  32000        4   research

In [ ]:
df

Ename  Eid    Sal  Dept_no         Dname
0  asha  201  50000        1  development 
1   anu  202  30000        2    accounting
2  arya  203  40909        3         sales
3   ram  204  32000        4     research 
4  anju  205  80000        5      Testing

#Modification
#df[cn][index ]=new value

In [ ]:
#df['Ename'][3]='vasu'

In [ ]:
df

Ename  Eid    Sal  Dept_no         Dname
0  asha  201  50000        1  development 
1   anu  202  30000        2    accounting
2  arya  203  40909        3         sales
3   ram  204  32000        4     research 
4  anju  205  80000        5      Testing

#Reading the files

In [ ]:
df=pd.read_csv('/content/sample_data/mnist_test.csv')

In [ ]:
df

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [ ]:
df=pd.read_csv('/content/annual-enterprise-survey-2023-financial-year-provisional.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/annual-enterprise-survey-2023-financial-year-provisional.csv'

In [ ]:
df

In [ ]:
df3=pd.read_excel('/content/colab links module 3.xlsx')
df3

In [ ]:
df4=pd.read_table('Pseudocode.txt')
df4