<a href="https://colab.research.google.com/github/AshaS591/Data-Analytics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([10,90,78,3+4j,'hi',100])
arr

array(['10', '90', '78', '(3+4j)', 'hi', '100'], dtype='<U64')

In [ ]:
arr1=np.array([56,7.8,90,-2-1j,'100',{1,2,3},{'a':100,'b':120}])
arr1

array([56, 7.8, 90, (-2-1j), '100', {1, 2, 3}, {'a': 100, 'b': 120}],
      dtype=object)

In [ ]:
arr1=np.array([1,5,7,40,9.0])

arr2=np.array([[1,7,9],
               [4,6,9],
               [99,89,79]])

arr3=np.array([[[1,9,10],
                [4,5,6]],

               [[9,10,56],
                [9,0,145]]])

In [ ]:
arr1

array([ 1.,  5.,  7., 40.,  9.])

In [ ]:
arr2

array([[ 1,  7,  9],
       [ 4,  6,  9],
       [99, 89, 79]])

In [ ]:
arr3

array([[[  1,   9,  10],
        [  4,   5,   6]],

       [[  9,  10,  56],
        [  9,   0, 145]]])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [ ]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

float64
int64
int64


In [ ]:
arr1.shape
arr2.shape
arr3.shape

(2, 2, 3)

In [ ]:
arr=np.array([1,2,8.9,56,78,90])
arr.shape
len(arr)
print(arr)
print()
arr1=arr.reshape(2,3)
arr1

[ 1.   2.   8.9 56.  78.  90. ]



array([[ 1. ,  2. ,  8.9],
       [56. , 78. , 90. ]])

In [ ]:
arr=np.array([[1,7,9,12],
              [5,7,9,13]])
arr.reshape(8,1)

arr

array([[ 1,  7,  9, 12],
       [ 5,  7,  9, 13]])

In [ ]:
arr.reshape(-1)
arr3.reshape(-1)

array([  1,   9,  10,   4,   5,   6,   9,  10,  56,   9,   0, 145])

In [ ]:
np.arange(1,100000)


np.arange(1000,1-1,-1)


arr=np.arange(1,7)

arr.reshape(1,6)
arr.reshape(6,1)
arr.reshape(2,3)
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#Task on array
# create an array b/w 0 to 1000 which contains only even values-->arange()
arr=np.arange(0,1001,2)
#create an array with char from 'A' to 'Z
out=[]
for i in range(65,91):
  out+=[chr(i)]
arr=np.array(out)
arr

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

In [ ]:
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [ ]:
np.linspace(0,1,1000)

array([0.        , 0.001001  , 0.002002  , 0.003003  , 0.004004  ,
       0.00500501, 0.00600601, 0.00700701, 0.00800801, 0.00900901,
       0.01001001, 0.01101101, 0.01201201, 0.01301301, 0.01401401,
       0.01501502, 0.01601602, 0.01701702, 0.01801802, 0.01901902,
       0.02002002, 0.02102102, 0.02202202, 0.02302302, 0.02402402,
       0.02502503, 0.02602603, 0.02702703, 0.02802803, 0.02902903,
       0.03003003, 0.03103103, 0.03203203, 0.03303303, 0.03403403,
       0.03503504, 0.03603604, 0.03703704, 0.03803804, 0.03903904,
       0.04004004, 0.04104104, 0.04204204, 0.04304304, 0.04404404,
       0.04504505, 0.04604605, 0.04704705, 0.04804805, 0.04904905,
       0.05005005, 0.05105105, 0.05205205, 0.05305305, 0.05405405,
       0.05505506, 0.05605606, 0.05705706, 0.05805806, 0.05905906,
       0.06006006, 0.06106106, 0.06206206, 0.06306306, 0.06406406,
       0.06506507, 0.06606607, 0.06706707, 0.06806807, 0.06906907,
       0.07007007, 0.07107107, 0.07207207, 0.07307307, 0.07407

In [ ]:
np.linspace(-50,10,500)

array([-5.00000000e+01, -4.98797595e+01, -4.97595190e+01, -4.96392786e+01,
       -4.95190381e+01, -4.93987976e+01, -4.92785571e+01, -4.91583166e+01,
       -4.90380762e+01, -4.89178357e+01, -4.87975952e+01, -4.86773547e+01,
       -4.85571142e+01, -4.84368737e+01, -4.83166333e+01, -4.81963928e+01,
       -4.80761523e+01, -4.79559118e+01, -4.78356713e+01, -4.77154309e+01,
       -4.75951904e+01, -4.74749499e+01, -4.73547094e+01, -4.72344689e+01,
       -4.71142285e+01, -4.69939880e+01, -4.68737475e+01, -4.67535070e+01,
       -4.66332665e+01, -4.65130261e+01, -4.63927856e+01, -4.62725451e+01,
       -4.61523046e+01, -4.60320641e+01, -4.59118236e+01, -4.57915832e+01,
       -4.56713427e+01, -4.55511022e+01, -4.54308617e+01, -4.53106212e+01,
       -4.51903808e+01, -4.50701403e+01, -4.49498998e+01, -4.48296593e+01,
       -4.47094188e+01, -4.45891784e+01, -4.44689379e+01, -4.43486974e+01,
       -4.42284569e+01, -4.41082164e+01, -4.39879760e+01, -4.38677355e+01,
       -4.37474950e+01, -

In [ ]:
import random
random.randint(1,5)

5

In [ ]:
a=np.random.randint(1,6)
a

np.random.randint(2,8.5,5)

array([5, 5, 4, 5, 7])

In [ ]:
np.random.rand(100)

array([0.79236334, 0.50489743, 0.33678988, 0.9420317 , 0.90701105,
       0.81880538, 0.386863  , 0.92962297, 0.61234378, 0.26009995,
       0.3460853 , 0.05063317, 0.45338684, 0.81544798, 0.3940549 ,
       0.20886432, 0.43446282, 0.22366578, 0.59759677, 0.62876672,
       0.34123548, 0.9902697 , 0.25374502, 0.65942065, 0.50733649,
       0.06972541, 0.18740371, 0.11911292, 0.29837558, 0.50546678,
       0.38820788, 0.75239773, 0.92194494, 0.2747356 , 0.95535857,
       0.2627566 , 0.69894436, 0.77479355, 0.03467629, 0.52964329,
       0.20389106, 0.65440878, 0.71429056, 0.58504276, 0.59716593,
       0.6785707 , 0.48904361, 0.52937245, 0.0680607 , 0.22456342,
       0.96837209, 0.28496544, 0.31244404, 0.89434091, 0.28189194,
       0.75073984, 0.66730391, 0.61313124, 0.40856516, 0.10092065,
       0.02815601, 0.93092476, 0.87986675, 0.91677105, 0.56950844,
       0.96969202, 0.83099693, 0.18731282, 0.28891663, 0.0419939 ,
       0.35991788, 0.80938379, 0.17491987, 0.99433481, 0.18702

In [ ]:
np.random.randn(200)

array([ 3.17982122e-01,  7.99519078e-01, -1.25824760e+00, -2.40705665e-01,
       -1.98404690e+00, -1.70655021e+00,  1.10620182e-01,  3.88732520e-02,
       -1.31380249e+00, -2.19711185e+00,  3.20470157e-01,  1.33835217e+00,
       -3.56137699e-01,  2.69758033e-01, -2.85502360e-01, -2.05913750e-01,
        1.32390806e+00, -1.33867803e+00,  7.66502728e-01, -7.25415962e-01,
       -1.68745569e+00,  1.14836846e+00, -7.96664047e-01, -1.00054534e+00,
        6.45760589e-01,  6.86019429e-01, -2.23739157e-01, -9.24877375e-01,
       -1.48107975e+00, -1.61074521e+00, -8.93099879e-01,  1.83846788e+00,
        2.08692003e+00,  2.29532720e-01, -1.49878753e-01,  2.90545738e-01,
        2.87865459e-01,  9.72167239e-02,  4.83308646e-01, -1.00062909e+00,
       -3.42553283e-01, -1.28472713e+00,  3.01577924e-01,  1.36976497e+00,
       -3.30830649e-01,  6.85494875e-01, -1.19901758e+00, -1.34894851e-01,
       -4.62838820e-02, -3.41104853e-02, -5.72807702e-01, -2.35758077e-01,
       -2.12052059e-01, -

In [ ]:
game=['rock','paper','scissor']
np.random.choice(game)

'scissor'

In [ ]:
songs=['blinding lights','perfect','night change','pushpa','wavin flag','chammak challo']
np.random.shuffle(songs)
songs[0]

'pushpa'

In [ ]:
np.zeros(50)
np.zeros((3,5))
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones(8)
np.ones((10,10))
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
np.identity(3)
np.identity(5)
np.identity(15)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [ ]:
np.random.randint(2,3,5)

array([2, 2, 2, 2, 2])

In [ ]:
arr1=np.array([10,20,40,90,{1,2,3}])
arr2=arr1.copy()
print(arr1)
print(arr2)

[10 20 40 90 {1, 2, 3}]
[10 20 40 90 {1, 2, 3}]


In [ ]:
print(id(arr1))
print(id(arr2))

138538636942992
138538636942512


In [ ]:
arr1[0]=1000
print(arr1)
print(arr2)

[1000 20 40 90 {1, 2, 3}]
[10 20 40 90 {1, 2, 3}]


In [ ]:
print(id(arr1[-1]))
print(id(arr2[-1]))

138538633932672
138538633932672


In [ ]:
arr1=np.array([[7,89,90],
               [5,7,8],
               [9,0,-23]])
arr2=arr1.copy()

print(arr1)
print()
print(arr2)

[[  7  89  90]
 [  5   7   8]
 [  9   0 -23]]

[[  7  89  90]
 [  5   7   8]
 [  9   0 -23]]


In [ ]:
print(id(arr1))
print(id(arr2))

138538636938672
138538636942992


In [ ]:
arr1[0][0]=700
print(arr1)
print(arr2)

[[700  89  90]
 [  5   7   8]
 [  9   0 -23]]
[[  7  89  90]
 [  5   7   8]
 [  9   0 -23]]


In [ ]:
print(id(arr1[0]))
print(id(arr2[0]))

138538636946256
138538636946256


In [ ]:
arr1[0]=[3,4,5]

print(arr1)
print()
print(arr2)

[[  3   4   5]
 [  5   7   8]
 [  9   0 -23]]

[[  7  89  90]
 [  5   7   8]
 [  9   0 -23]]


In [ ]:
#indexing on 1D array
arr=np.array([1.5,36,78,99,175])
arr[-1]
arr[3]
arr[0]
arr[-2]
arr[-4]

36.0

In [ ]:
arr=np.array([[13,65,79],
              [77,67,81],
              [71,56,99]])
arr[2][0]

arr[2,0]
arr[2,1]


arr[0,2]

arr[1,2]

81

In [ ]:
arr=np.array([[[1,2,3,6],
               [4,5,7,9]],

          [[8,9,70,90],
           [5,6,7,8]]])
arr

array([[[ 1,  2,  3,  6],
        [ 4,  5,  7,  9]],

       [[ 8,  9, 70, 90],
        [ 5,  6,  7,  8]]])

In [ ]:
arr[0,0,1]
arr[0,1,3]


arr[1,0,3]

90

In [ ]:
#slicing on arrays

arr=np.array([1.5,36,78,99,175])
arr

array([  1.5,  36. ,  78. ,  99. , 175. ])

In [ ]:
arr[0:3]


arr[:3]

arr[2:]

arr[::-1]

arr[::2]


arr[1::2]

array([36., 99.])

In [ ]:
arr=np.array([[13,65,79],
              [77,67,81],
              [71,56,99]])

arr[0:2,0:2]

arr[1:,1:]

arr[0:2,:]

arr[1:2,:]


arr[::2,:]

arr[:,::2]

arr[::-1,:]


arr[:,::-1]

arr[::-1,::-1]

array([[99, 56, 71],
       [81, 67, 77],
       [79, 65, 13]])

In [ ]:
arr=np.array([[[1,2,3,6],
               [4,5,7,9]],

          [[8,9,70,90],
           [5,6,7,8]]])


arr[0:1,0:1,0:3]


arr[0:1,0:,0:2]

array([[[1, 2],
        [4, 5]]])

In [ ]:
arr1=np.array([[1,2,3],
               [7,8,9],
               [9,0,5]])
arr2=arr1.copy()
print(arr1)
print()
print(arr2)

[[1 2 3]
 [7 8 9]
 [9 0 5]]

[[1 2 3]
 [7 8 9]
 [9 0 5]]


In [ ]:
print(id(arr1))
print(id(arr2))

138538636945008
138538636067056


In [ ]:
print(id(arr1[0]))
print(id(arr2[0]))
print()
print(id(arr1[1]))
print(id(arr2[1]))
print()
print(id(arr1[2]))
print(id(arr2[2]))

138538636067344
138538636067344

138538636067344
138538636067344

138538636067344
138538636067344


In [ ]:
arr1[0]=1000
arr1

array([[1000, 1000, 1000],
       [   7,    8,    9],
       [   9,    0,    5]])

In [ ]:
arr1=np.array([[1,2,3],
               [7,8,9],
               [9,0,5]])
arr2=arr1.view()

print(arr1)
print()
print(arr2)

[[1 2 3]
 [7 8 9]
 [9 0 5]]

[[1 2 3]
 [7 8 9]
 [9 0 5]]


In [ ]:
print(id(arr1))
print(id(arr2))

138538636075792
138538636068400


In [ ]:
arr1[0][0]=1000

print(arr1)
print()
print(arr2)

[[1000    2    3]
 [   7    8    9]
 [   9    0    5]]

[[1000    2    3]
 [   7    8    9]
 [   9    0    5]]


In [ ]:
#array with array

#1) Arithmatic operators

arr1=np.arange(1,8)
arr2=np.arange(10,17)
print(arr1)
print(arr2)




[1 2 3 4 5 6 7]
[10 11 12 13 14 15 16]


In [ ]:
arr1+arr2
arr1-arr2
arr1*arr2
arr1/arr2

array([0.1       , 0.18181818, 0.25      , 0.30769231, 0.35714286,
       0.4       , 0.4375    ])

In [ ]:
arr1=np.array([[1,2,3],
               [7,8,9],
               [9,0,5]])
arr2=np.array([[3,4,5],[5,6,7],[9,0,8]])

arr1+arr2
arr1*arr2
arr1/arr2
arr1//arr2
arr1%arr2
arr1**arr2

<ipython-input-59-2c72e51c7a95>:8: RuntimeWarning: invalid value encountered in divide
  arr1/arr2
<ipython-input-59-2c72e51c7a95>:9: RuntimeWarning: divide by zero encountered in floor_divide
  arr1//arr2
<ipython-input-59-2c72e51c7a95>:10: RuntimeWarning: divide by zero encountered in remainder
  arr1%arr2


array([[        1,        16,       243],
       [    16807,    262144,   4782969],
       [387420489,         1,    390625]])

In [ ]:
arr1=np.arange(0,7)
arr2=np.arange(10,17)
print(arr1)
print(arr2)


[0 1 2 3 4 5 6]
[10 11 12 13 14 15 16]


In [ ]:
arr1&arr2

arr1|arr2

arr1^arr2
~arr2
~arr1


arr1<<arr2

arr1>>arr2

array([0, 0, 0, 0, 0, 0, 0])

In [ ]:
10 in arr2


arr1 not in arr2

20 not in arr2

True

In [ ]:
arr1.all() and arr2.all()
arr1.any() and arr2.any()

True

In [ ]:
arr1=np.array([100])
arr2=np.array([500])

arr1 and arr2


array([500])

In [ ]:
# arr1

In [ ]:
arr1=np.arange(10,17)


arr1

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
arr1+2

2+arr1

arr1-10
arr1*30
arr1/40

arr1//35

arr1%3

arr1**2


100 in arr1

arr1


20 not in arr1

True

In [ ]:
arr1&5
arr1|2
# arr1&3
arr1^3
arr1<<3
arr1>>2


arr1+(3+4j)

2**arr1


arr1**2

array([100, 121, 144, 169, 196, 225, 256])

In [ ]:
print(arr1+2)
print(2+arr1)

print(2-arr1)




[12 13 14 15 16 17 18]
[12 13 14 15 16 17 18]


In [ ]:
arr1=np.array([[1,2,3],
               [7,8,9],
               [9,0,5]])
arr1**2

array([[ 1,  4,  9],
       [49, 64, 81],
       [81,  0, 25]])

In [ ]:
arr1+=2
arr1=arr1+2
arr1

array([[ 5,  6,  7],
       [11, 12, 13],
       [13,  4,  9]])

In [ ]:
#Inbuilt functions on arrays

arr=np.arange(-10,11)
arr

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
arr.min()
min(arr)

arr.max()
max(arr)

arr.sum()
sum(arr)


arr.mean()

np.abs(arr)

arr1=abs(arr)
arr1

-abs(arr1)

len(arr)


np.sin(arr)
np.cos(arr)
np.tan(arr)

array([-0.64836083,  0.45231566,  6.79971146, -0.87144798,  0.29100619,
        3.38051501, -1.15782128,  0.14254654,  2.18503986, -1.55740772,
        0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])