<a href="https://colab.research.google.com/github/AshaS591/Data-Analytics/blob/main/practice_numpy__and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import pandas as pd

In [19]:
collection=[12,4,5,6,79,9]
arr=np.array(collection)
arr

array([12,  4,  5,  6, 79,  9])

In [20]:
items=['asha','anu',12,67]
arr1=np.array(items)
arr1

array(['asha', 'anu', '12', '67'], dtype='<U21')

In [21]:
avg=arr.mean()
avg

19.166666666666668

In [22]:
arr.ndim

1

In [23]:
arr.shape

(6,)

In [24]:
arr.dtype

dtype('int64')

In [25]:
arr1.dtype

dtype('<U21')

In [27]:
new=arr.reshape(3,2)
new

array([[12,  4],
       [ 5,  6],
       [79,  9]])

In [33]:
res=new.reshape(3,1,2)
res

array([[[12,  4]],

       [[ 5,  6]],

       [[79,  9]]])

In [35]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [36]:
arr=np.linspace(1,20,10)
arr

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [39]:
arr=np.random.rand(10)
arr

array([0.64734224, 0.23750674, 0.38574154, 0.4808388 , 0.32827247,
       0.80815844, 0.06930822, 0.02830652, 0.52197863, 0.02824966])

In [42]:
arr=np.random.randn(10)
arr

array([-1.14036388,  0.16894627,  0.81753679, -2.51889484,  1.49187056,
        0.63088856,  0.49751331, -0.27909837, -0.10718252, -1.2303011 ])

In [44]:
arr=np.random.randint(10,30,5)
arr

array([24, 28, 19, 13, 21])